image: snakemake/snakemake-tutorial:stable
tasts:
  - init: Cleanup tutorial environment
    command: rm Snakefile .gitpod.yml upload_google_storage.py Dockerfile
  - activate-env: Activate environment
    command: conda activate snakemake-tutorial
