channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=7.4
  - jinja2
  - matplotlib
  - graphviz
  - bcftools =1.14
  - samtools =1.14
  - bwa =0.7.17
  - pysam =0.17
  - pygments
