channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=6.11
  - jinja2
  - networkx
  - matplotlib
  - graphviz
  - bcftools
  - samtools
  - bwa
  - pysam
  - pygraphviz
  - pygments
