channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=6.11
  - jinja2
  - networkx
  - matplotlib
  - graphviz
  - bcftools =1.14
  - samtools =1.14
  - bwa =0.7.17
  - pysam =0.17
  - pygraphviz
  - pygments
