channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake =3.11.0
  - python =3.6
  - jinja2 =2.10
  - networkx =2.1
  - graphviz =2.38.0
  - bcftools =1.3.1
  - samtools =1.3.1
  - bwa =0.7.12
